#!/usr/bin/env bash
# Generate the Homebrew formula for a published indice release, pinning the
# per-platform release tarballs and their SHA-256 sums. Prints the formula to
# stdout; redirect it into the tap, e.g.:
#
#   scripts/homebrew-formula.sh v0.1.0 > ../homebrew-indice/Formula/indice.rb
#
# With no argument it uses the latest published release. Needs the `gh` CLI.
set -euo pipefail

repo="edsu/indice"
tag="${1:-$(gh release view --repo "$repo" --json tagName -q .tagName)}"

# Homebrew slot -> Rust target triple (macOS + Linux; Windows is Scoop's job).
macos_arm=aarch64-apple-darwin
macos_intel=x86_64-apple-darwin
linux_arm=aarch64-unknown-linux-gnu
linux_intel=x86_64-unknown-linux-gnu

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
gh release download "$tag" --repo "$repo" --dir "$tmp" --pattern '*.tar.gz.sha256'

url() { printf 'https://github.com/%s/releases/download/%s/indice-%s-%s.tar.gz' "$repo" "$tag" "$tag" "$1"; }
sha() { # $1 = target triple; the .sha256 file is "<hash>  <filename>"
  local f="$tmp/indice-${tag}-$1.tar.gz.sha256"
  [ -f "$f" ] || { echo "missing checksum for $1 ($f) — is the release built?" >&2; exit 1; }
  awk '{print $1}' "$f"
}

cat <<EOF
# Generated by scripts/homebrew-formula.sh — do not edit by hand.
class Indice < Formula
  desc "Web archive server: WACZ indexing, full-text search, and replay"
  homepage "https://github.com/${repo}"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "$(url "$macos_arm")"
      sha256 "$(sha "$macos_arm")"
    end
    on_intel do
      url "$(url "$macos_intel")"
      sha256 "$(sha "$macos_intel")"
    end
  end

  on_linux do
    on_arm do
      url "$(url "$linux_arm")"
      sha256 "$(sha "$linux_arm")"
    end
    on_intel do
      url "$(url "$linux_intel")"
      sha256 "$(sha "$linux_intel")"
    end
  end

  def install
    bin.install "indice"
  end

  test do
    assert_match "indice", shell_output("#{bin}/indice --help")
  end
end
EOF
